- name: Copy Go certificate
  copy:
    src: linux_signing_key.pub
    dest: /tmp/golang.pub

- name: Install Go certificate
  command: gpg --import /tmp/golang.pub

- name: Download signature
  get_url:
    url: "{{ go_tarball_url }}.asc"
    dest: "{{ go_download_dir }}"

- name: Verify the signature
  shell: gpg --verify "{{ go_tarball_name }}.asc" "{{ go_tarball_name }}"
  args:
    chdir: "{{ go_download_dir }}"